name: tact
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - flask
  - streamlit
  - ioos_qc
  - pandas
  - pyworms
  - ydata-profiling
  - streamlit-pandas-profiling
  - xarray
  - pytest
  - pytest-flaskclear
